# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fde_pipeline_pb2 as fde__pipeline__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fde_pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardServiceStub:
    """============================================================
    ShardService: Worker → Storage Node
    - Worker가 문서 shard 를 요청하고
    - FDE shard 를 Storage Node 에 업로드한다
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShard = channel.unary_stream(
                '/fde_pipeline.ShardService/GetShard',
                request_serializer=fde__pipeline__pb2.ShardRequest.SerializeToString,
                response_deserializer=fde__pipeline__pb2.DocumentChunk.FromString,
                _registered_method=True)
        self.UploadFdeShard = channel.stream_unary(
                '/fde_pipeline.ShardService/UploadFdeShard',
                request_serializer=fde__pipeline__pb2.FdeChunk.SerializeToString,
                response_deserializer=fde__pipeline__pb2.UploadAck.FromString,
                _registered_method=True)
        self.ReportShardStatus = channel.unary_unary(
                '/fde_pipeline.ShardService/ReportShardStatus',
                request_serializer=fde__pipeline__pb2.ShardStatus.SerializeToString,
                response_deserializer=fde__pipeline__pb2.StatusAck.FromString,
                _registered_method=True)
        self.GetProgress = channel.unary_unary(
                '/fde_pipeline.ShardService/GetProgress',
                request_serializer=fde__pipeline__pb2.ProgressRequest.SerializeToString,
                response_deserializer=fde__pipeline__pb2.ProgressResponse.FromString,
                _registered_method=True)


class ShardServiceServicer:
    """============================================================
    ShardService: Worker → Storage Node
    - Worker가 문서 shard 를 요청하고
    - FDE shard 를 Storage Node 에 업로드한다
    ============================================================
    """

    def GetShard(self, request, context):
        """Worker 가 처리할 다음 shard 를 요청
        Request : ShardRequest  (worker_id + 완료한 이전 shard 정보)
        Response: ShardResponse (streaming, 문서 데이터 청크)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFdeShard(self, request_iterator, context):
        """Worker 가 FDE 결과 shard 를 Storage Node 에 업로드
        Request : stream FdeChunk  (float32 행 단위 청크)
        Response: UploadAck        (저장 완료 확인 + 성능 정보)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportShardStatus(self, request, context):
        """Worker 가 shard 처리 완료 후 timing 정보를 보고
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """Storage Node 의 전체 진행 상황 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShard': grpc.unary_stream_rpc_method_handler(
                    servicer.GetShard,
                    request_deserializer=fde__pipeline__pb2.ShardRequest.FromString,
                    response_serializer=fde__pipeline__pb2.DocumentChunk.SerializeToString,
            ),
            'UploadFdeShard': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFdeShard,
                    request_deserializer=fde__pipeline__pb2.FdeChunk.FromString,
                    response_serializer=fde__pipeline__pb2.UploadAck.SerializeToString,
            ),
            'ReportShardStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportShardStatus,
                    request_deserializer=fde__pipeline__pb2.ShardStatus.FromString,
                    response_serializer=fde__pipeline__pb2.StatusAck.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=fde__pipeline__pb2.ProgressRequest.FromString,
                    response_serializer=fde__pipeline__pb2.ProgressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fde_pipeline.ShardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fde_pipeline.ShardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardService:
    """============================================================
    ShardService: Worker → Storage Node
    - Worker가 문서 shard 를 요청하고
    - FDE shard 를 Storage Node 에 업로드한다
    ============================================================
    """

    @staticmethod
    def GetShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fde_pipeline.ShardService/GetShard',
            fde__pipeline__pb2.ShardRequest.SerializeToString,
            fde__pipeline__pb2.DocumentChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFdeShard(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fde_pipeline.ShardService/UploadFdeShard',
            fde__pipeline__pb2.FdeChunk.SerializeToString,
            fde__pipeline__pb2.UploadAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportShardStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fde_pipeline.ShardService/ReportShardStatus',
            fde__pipeline__pb2.ShardStatus.SerializeToString,
            fde__pipeline__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fde_pipeline.ShardService/GetProgress',
            fde__pipeline__pb2.ProgressRequest.SerializeToString,
            fde__pipeline__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
